### PR TITLE
psyneu-69: chore: added visualize menu to mechs

### PR DESCRIPTION
**Pull request by emekauja**
Implement add to visualization dialog for mechanism and compositions
Screenshot 2023-06-15 at 11 12 24 PM

### CODE REVIEW

**Review by ddelpiano — CHANGES_REQUESTED** [review]
Please review the metadata components, the fact that we are copy-pasting the same snippet of code 24 times is not acceptable.
Factor out from the mechmetadata what is common for all the classes and leave inside this component only what is custom for each class.
Thanks!

**Comment by emekauja** [comment]
hi @dario the snippet copied is simple state management for the menu which is expected to be different for each mechanism metadata as each metadata data will add the users selected values to its options, also the add visualize menu is a component reusable across board, there is no visualization  data or options yet so I used the same logic for now,
moved the function logic which are duplicate to utils for now and when we need to something different we can

**Comment by ddelpiano** [comment]
@emekauja let's take these 2 components in analysis.

https://github.com/MetaCell/PsyNeuLinkView/blob/14914dc7657e1dee1c24c4728998a6d80edd0f7d/src/client/components/views/editView/mechanisms/AGTControlMechanism/MechMetadata.js

and 

https://github.com/MetaCell/PsyNeuLinkView/blob/14914dc7657e1dee1c24c4728998a6d80edd0f7d/src/client/components/views/editView/mechanisms/AutoLearningMechanism/MechMetadata.js

There are some imports that differ, depending on the type of inputs that we need to display for each of them, we can agree on that.

Styling, constructor and useEffect function are the same

```
const styles = {
  textColor: {
    color: vars.functionTextColor,
  },
  codeColor: {
    color: vars.functionCodeColor,
  },
};

function MechMetadata(props) {
  const {
    model,
    model: { options },
    engine,
    changeVisibility,
    onUpdateOptions,
  } = props;

  const [optionsValue, updateOptions] = React.useState(() => options);
  const optionKeys = toObject(Object.entries(options));
  const [value, updateValue] = React.useState(() => ['Composition 2']);

  React.useEffect(() => {
    debounceUpdateValue(optionsValue, onUpdateOptions);
  }, [onUpdateOptions, optionsValue]);
```

inside the return, the logic that wraps the component within the NodeSelection component is the same and the logic for the icon is the same for all, with some differences for the icon but you can steal that part already from the MechSimple that I refactored.
As well the MetaDataInput for the name of the Mechanism is the same for all as well as the Port list component at the bottom and at the end.

```
return (
    <Box className={`primary-node rounded ${options.variant}`}>
      {options.selected && (
        <NodeSelection
          node={model}
          engine={engine}
          text={'Hide properties'}
          changeVisibility={changeVisibility}
        />
      )}
      <Box className="primary-node_header">
        <Box className="icon-wrapper">
          <ControlMechIcon />
        </Box>

        <Box display="inline-flex" alignItems="center" component="p">
          <MetaDataInput
            textAlign="center"
            value={optionsValue.name}
            onChange={(e) =>
              handleOptionChange(
                { key: optionKeys.name, value: e.target.value },
                updateOptions
              )
            }
          />
        </Box>
      </Box>

      <PortsList
        ports={options.ports}
        portType={PortTypes.INPUT_PORT}
        engine={engine}
        model={model}
      />

      <Box className="seprator" />

....
....
      <Box className="seprator" />

      <PortsList
        ports={options.ports}
        portType={PortTypes.OUTPUT_PORT}
        engine={engine}
        model={model}
        direction="right"
      />
    </Box>
```

What's inside the Box block-wrapper is really the custom part of the metadata view, and that is what should present inside this component, all the rest can be factored out, again to avoid to have to fix and implement a feature 24 times in 24 different files.

Thanks!

**Comment by ddelpiano** [comment]
@emekauja there is still one problem that is the fact that these forms are not connected to the model (options) itself, so when serialising nothing of the new data is saved, I will take care of this.
Thx

**Comment by emekauja** [comment]
@ddelpiano theres an updateOptions callback we can leverage on the metadata, that's the thought around the denounce update options

**Review by ddelpiano — APPROVED** [review]

**Pull request merged**
